App\DTO\RegistrationDTO:
    properties:
        username:
            - NotBlank:
                message: Veuillez choisir un pseudo.
            - Length:
                max: 50
                maxMessage: Maximun {{ limit }} caractères.

        password:
            - NotBlank:
                  message: Veuillez saisir un mot de passe.
            - Length:
                  max: 255
                  maxMessage: Maximun {{ limit }} caractères.
            - EqualTo:
                  propertyPath: confirmPassword
                  message: Les mots de passe ne sont pas identique.

        confirmPassword:
            - NotBlank:
                  message: Veuillez confirmer votre mot de passe.
            - Length:
                  max: 255
                  maxMessage: Maximun {{ limit }} caractères.
            - EqualTo:
                propertyPath: password
                message:

        email:
            - NotBlank:
                  message: Veuillez saisir une adresse email.
            - Email:
                  message: Le format de l'adresse email est invalide.


