App\DTO\VideoDTO:
    properties:
        url:
            - Regex:
                pattern: '#^(http|https)://(www.youtube.com|www.dailymotion.com|vimeo.com)/#'
                match: true
                message: L'url doit correspondre à l'url d'une vidéo Youtube ou  DailyMotion.